-- Condizioni fornitura
INSERT INTO distributors (nome, min_ordine, spese_spedizione, spese_ghiaccio_secco) VALUES
('Beckman Coulter Srl', '/', '50 €', '/'),
('Bio-Techne s.r.l.', '/', '/', '50 €'),
('Campoverde', '/', '42 € (nulle su Milano)', '15 €'),
('D.B.A.', '/', '€ 20 (+IVA) per ordini < € 500 (IVA esclusa)', '30 €'),
('Diatech Lab Line srl', '150 €', '/', '/'),
('D.I.D. Diagnostic International Distribution Spa', '/', '€ 40 per ordini < € 350', '25 €'),
('Eppendorf', '/', '€ 35 (+IVA) per ordini < € 500 (IVA esclusa)', '/'),
('Gilson Italia s.r.l.', '300 €', '€ 50 (+IVA) per ordini < € 500 (IVA esclusa)', '/'),
('MedChemTronica', '/', '/', '/'),
('Qiagen', '/', '€ 40 (+IVA) per ordini < € 1000; € 38 (+IVA) per ordini < € 400', '24 €'),
('Sarstedt', 'superiore a 200 € (IVA esclusa)', '€ 25 (+IVA) per ordini < € 300 (IVA esclusa)', '/'),
('Tema Ricerca', '/', '€ 20 (+IVA) per ordini < € 400 (IVA esclusa)', '30 €'),
('Bio-Rad', '/', '/', '/'),
('Promega', '/', '€ 50 (+IVA) per ordini < € 400 (IVA esclusa)', '€ 30 (+IVA) per ordini < € 400'),
('AGILENT TECHNOLOGIES ITALIA SPA', '/', '/', '/'),
('Carlo Erba Reagents Srl', '50 €', 'CONTR.SPESE GEST. 50-200€ = €65+IVA; 200-500€ = €48+IVA; HORIZON = €40+IVA; METABION = €18+IVA', 'Ghiaccio secco €30+IVA; CPA €70+IVA'),
('Euroclone S.p.A.', '150 €', '/', 'Nessuna spesa eccetto azoto liquido dewar: 450 €'),
('Merck Life Science S.R.L.', '/', '/', '55 €'),
('REVVITY ITALIA SPA', '/', 'variabile in base all''ordine', 'variabile in base all''ordine'),
('SARTORIUS ITALY SRL', '/', '28 € (per ordini < 500 €)', '/'),
('S.I.A.L. S.r.l.', '/', '20 € per ordini < 200 € (IVA esclusa)', '20 € per ordini < 200 € (IVA esclusa)'),
('VWR International S.r.l.', 'minimo 400 € (IVA esclusa), altrimenti €30 gestione', 'Ordini < 400 €: €30; Ordini > 400 €: gratuito', '/'),
('Starlab', '100 €', '€ 40 per ordini < € 400', '/'),
('Twin Helix srl', '100 €', '€ 25 per ordini < € 250', '30 €'),
('2Biological Instruments', '150 €', '€ 25 per ordini < € 500', '/'),
('Aurogene', '500 €', '€ 25 (+IVA) per ordini < € 500 (IVA esclusa)', '/'),
('Life Technologies (ThermoFisher)', '/', 'Ordini < €2000: €48+IVA; Hazardous: €48+IVA; Oligo tubi: €12+IVA; Oligo piastre: €70+IVA', '€ 48+IVA'),
('Roche', '/', '€ 30 per ordini < € 300', '/'),
('Illumina', '/', '150 €', '/'),
('TebuBio', '/', '€ 30 (+IVA) per ordini < € 100 (IVA esclusa); assicurazione per ordini > €10.000', '€ 52 ghiaccio secco; € 255 azoto liquido'),
('Miltenyi', '/', '€ 35 (+IVA) per ordini < € 500 (IVA esclusa)', '/'),
('BECTON DICKINSON ITALIA S.p.A.', '/', '€ 50+IVA standard; €75+IVA espresso; €35 per ordini < €1000', '/'),
('Eurofins Genomics Italy S.r.l.', '/', 'gratuite', '/'),
('LGC Standards', '/', '/', '/'),
('PRODOTTI GIANNI', '/', '€ 29 (IVA esclusa) spese gestione; nessuna spesa per ordini > 600 €', 'Temperatura ambiente/wet ice: 0€; Ghiaccio secco: 20€; DataLogger: 60€; HAZARD: 40€');


-- Brands distribuiti
INSERT INTO distributor_brands (distributore, brand, esclusiva) VALUES
-- D.B.A.
('D.B.A.', 'VectorLabs', FALSE),
('D.B.A.', 'SYNAPTIC SYSTEMS (SYSY)', FALSE),
('D.B.A.', 'CLOUD CLONE', FALSE),
('D.B.A.', 'Applichem', FALSE),
('D.B.A.', 'PTGLAB', FALSE),
('D.B.A.', 'BIORBYT', FALSE),
('D.B.A.', 'MEDCHEM', FALSE),
('D.B.A.', 'ASSAYGENIE', FALSE),
('D.B.A.', 'PEPROTECH', FALSE),

-- Agilent
('Agilent', 'Agilent', TRUE),

-- Aurogene (esclusiva)
('Aurogene', 'InvivoGen', TRUE),
('Aurogene', 'Selleck', TRUE),
('Aurogene', 'Diagenode', TRUE),
('Aurogene', 'Cytek', TRUE),
('Aurogene', 'Bioss', TRUE),
('Aurogene', 'OZBioscience', TRUE),
('Aurogene', 'Zymo', TRUE),
('Aurogene', 'Mabtech', TRUE),
('Aurogene', 'Abclonal', TRUE),
('Aurogene', 'Akadeum', TRUE),
('Aurogene', 'Bioline', TRUE),
('Aurogene', 'CellGS', TRUE),
('Aurogene', 'Azure', TRUE),
('Aurogene', 'Advasta', TRUE),
-- Aurogene (non esclusiva)
('Aurogene', 'Biotium', FALSE),
('Aurogene', 'Innovative', FALSE),
('Aurogene', 'Cusabio', FALSE),
('Aurogene', 'Krishgen', FALSE),
('Aurogene', 'Mybiosource', FALSE),
('Aurogene', 'Santa Cruz', FALSE),
('Aurogene', 'SouthernBiotech', FALSE),
('Aurogene', 'Bethyl', FALSE),
('Aurogene', 'Atlas', FALSE),
('Aurogene', 'Biolegend', FALSE),
('Aurogene', 'Leinco', FALSE),
('Aurogene', 'Invent', FALSE),
('Aurogene', 'DSHB', FALSE),
('Aurogene', 'Worthington', FALSE),
('Aurogene', 'GVS', FALSE),
('Aurogene', 'Biowest', FALSE),
('Aurogene', 'Finetest', FALSE),
('Aurogene', 'Cell Signaling', FALSE),
('Aurogene', 'Serva', FALSE),

-- BECKMAN COULTER
('BECKMAN COULTER S.r.L.', 'Beckman Coulter', TRUE),

-- Bio-Rad
('Bio-Rad', 'Bio-Rad', TRUE),

-- Bio-Techne
('Bio-Techne', 'BULK - ELLA cartridges', FALSE),
('Bio-Techne', 'ACD', FALSE),

-- Campoverde
('Campoverde srl', 'BioLegend', FALSE),
('Campoverde srl', 'Arrow Biotech (ex-CTSV)', FALSE),

-- Diatech Lab Line (esclusiva)
('Diatech Lab Line srl', 'Takara Bio Inc.', TRUE),
('Diatech Lab Line srl', 'Bruker Spatial Biology Inc.', TRUE),
('Diatech Lab Line srl', 'Mission Bio', TRUE),
('Diatech Lab Line srl', 'DeNovix Inc.', TRUE),
('Diatech Lab Line srl', 'RBC Bioscience Corporation', TRUE),
('Diatech Lab Line srl', 'Next Advance Inc.', TRUE),
('Diatech Lab Line srl', 'Singleron Biotechnologies', TRUE),
('Diatech Lab Line srl', 'Watchmaker Genomics', TRUE),
('Diatech Lab Line srl', 'Twist Bioscience', TRUE),
('Diatech Lab Line srl', 'EMQN', TRUE),
-- Diatech Lab Line (non esclusiva)
('Diatech Lab Line srl', 'Grant Instruments', FALSE),
('Diatech Lab Line srl', 'Aline Biosciences', FALSE),
('Diatech Lab Line srl', 'Biosan', FALSE),
('Diatech Lab Line srl', 'Capp Denmark', FALSE),
('Diatech Lab Line srl', 'Labnet International Inc.', FALSE),
('Diatech Lab Line srl', 'Zybio Inc.', FALSE),
('Diatech Lab Line srl', 'SSI Bio', FALSE),
('Diatech Lab Line srl', 'YouSeq Ltd', FALSE),
('Diatech Lab Line srl', 'SoftGenetics LLC', FALSE),
('Diatech Lab Line srl', 'Luna Nanotech Inc.', FALSE),
('Diatech Lab Line srl', 'SeqOne S.A.S.', FALSE),
('Diatech Lab Line srl', 'BioSkryb Genomics Inc.', FALSE),
('Diatech Lab Line srl', 'Sensoquest Gmbh', FALSE),

-- D.I.D.
('D.I.D. Diagnostic International Distribution Spa', 'StemCell Technologies', TRUE),
('D.I.D. Diagnostic International Distribution Spa', 'MBL', TRUE),
('D.I.D. Diagnostic International Distribution Spa', 'Minerva Biolabs', TRUE),
('D.I.D. Diagnostic International Distribution Spa', 'Biolamina', TRUE),
('D.I.D. Diagnostic International Distribution Spa', 'Biowest', TRUE),

-- Carlo Erba (esclusiva)
('CARLO ERBA REAGENTS SRL', 'Carlo Erba Reagents', TRUE),
('CARLO ERBA REAGENTS SRL', 'FASTER', TRUE),
('CARLO ERBA REAGENTS SRL', 'METABION International AG', TRUE),
('CARLO ERBA REAGENTS SRL', 'MICROSYNTH AG', TRUE),
('CARLO ERBA REAGENTS SRL', 'VIZGEN', TRUE),
('CARLO ERBA REAGENTS SRL', 'GS BIOTECH', TRUE),
('CARLO ERBA REAGENTS SRL', 'JET BIOFIL', TRUE),
-- Carlo Erba (non esclusiva)
('CARLO ERBA REAGENTS SRL', 'MACHEREY NAGEL GmbH', FALSE),
('CARLO ERBA REAGENTS SRL', 'HORIZON - DHARMACON', FALSE),
('CARLO ERBA REAGENTS SRL', 'LLG', FALSE),
('CARLO ERBA REAGENTS SRL', 'Thermo Fisher Scientific (ACROS Organics, ALFA AESAR, Fisher BioReagents, Maybridge)', FALSE),
('CARLO ERBA REAGENTS SRL', 'GLENTHAM LIFE SCIENCE', FALSE),
('CARLO ERBA REAGENTS SRL', 'CPAchem', FALSE),
('CARLO ERBA REAGENTS SRL', 'BRAND GMBH', FALSE),
('CARLO ERBA REAGENTS SRL', 'EVERMED', FALSE),
('CARLO ERBA REAGENTS SRL', 'LABOR SECURITY SYSTEM', FALSE),
('CARLO ERBA REAGENTS SRL', 'SCALE Biosciences', FALSE),
('CARLO ERBA REAGENTS SRL', 'LEVITASBIO', FALSE),
('CARLO ERBA REAGENTS SRL', 'AZENTA (4tiTUDE)', FALSE),
('CARLO ERBA REAGENTS SRL', 'PROMOCELL', FALSE),
('CARLO ERBA REAGENTS SRL', 'SOLIS BIODYNE', FALSE),
('CARLO ERBA REAGENTS SRL', 'Thermo Fisher Scientific Baltics UAB (Fermentas)', FALSE),
('CARLO ERBA REAGENTS SRL', 'Thermo Fisher Scientific (Thermo Fisher OY, NUNC, MBP)', FALSE),
('CARLO ERBA REAGENTS SRL', 'LNI', FALSE),

-- Euroclone (esclusiva)
('Euroclone S.p.A.', '10X Genomics', TRUE),
('Euroclone S.p.A.', 'BMG Labtech', TRUE),
('Euroclone S.p.A.', 'Cedarlane Labs', TRUE),
('Euroclone S.p.A.', 'Cell Signaling Technology', TRUE),
('Euroclone S.p.A.', 'Covaris', TRUE),
('Euroclone S.p.A.', 'Euroclone Brand', TRUE),
('Euroclone S.p.A.', 'IMPLEN', TRUE),
('Euroclone S.p.A.', 'LONZA', TRUE),
('Euroclone S.p.A.', 'MGI', TRUE),
('Euroclone S.p.A.', 'NAVINCI', TRUE),
('Euroclone S.p.A.', 'NEW ENGLAND BIOLABS', TRUE),
('Euroclone S.p.A.', 'System Biosciences', TRUE),
-- Euroclone (non esclusiva)
('Euroclone S.p.A.', 'Applied Cells', FALSE),
('Euroclone S.p.A.', 'BiOptic', FALSE),
('Euroclone S.p.A.', 'Bioreba', FALSE),
('Euroclone S.p.A.', 'Capp-AHN', FALSE),
('Euroclone S.p.A.', 'Corning - Falcon', FALSE),
('Euroclone S.p.A.', 'Cytiva - GEA', FALSE),
('Euroclone S.p.A.', 'Enzo Life Sciences', FALSE),
('Euroclone S.p.A.', 'Greiner BioOne', FALSE),
('Euroclone S.p.A.', 'ITW reagents (Applichem - Panreac)', FALSE),
('Euroclone S.p.A.', 'Jackson ImmunoResearch', FALSE),
('Euroclone S.p.A.', 'Magtivio', FALSE),
('Euroclone S.p.A.', 'Polyplus-Transfection', FALSE),
('Euroclone S.p.A.', 'Roche', FALSE),
('Euroclone S.p.A.', 'Sigma Zentrifugen', FALSE),
('Euroclone S.p.A.', 'Zymo', FALSE),

-- Gilson
('GILSON', 'GILSON', TRUE),

-- Merck
('Merck Life Science S.R.L', 'Merck/SigmaAldrich/Supelco/Millipore', FALSE),
('Merck Life Science S.R.L', 'Corning/Falcon/Axygen', FALSE),
('Merck Life Science S.R.L', 'Cytiva/Whatman', FALSE),
('Merck Life Science S.R.L', 'Eppendorf', FALSE),
('Merck Life Science S.R.L', 'Brand', FALSE),
('Merck Life Science S.R.L', 'Roche/KAPA', FALSE),
('Merck Life Science S.R.L', 'Avanti Polar Lipids', FALSE),
('Merck Life Science S.R.L', 'Hettich', FALSE),
('Merck Life Science S.R.L', 'IKA', FALSE),
('Merck Life Science S.R.L', 'Greiner', FALSE),
('Merck Life Science S.R.L', 'NUNC', FALSE),
('Merck Life Science S.R.L', 'Hamilton', FALSE),
('Merck Life Science S.R.L', 'Wilmad', FALSE),

-- Revvity
('Revvity Italia', 'Revvity Inc.', TRUE),

-- Sartorius
('SARTORIUS ITALY SRL', 'SARTORIUS INSTRUMENTS GmbH', TRUE),
('SARTORIUS ITALY SRL', 'SARTORIUS STEDIM BIOTECH GmbH', TRUE),

-- SIAL (esclusiva)
('SIAL', 'Analytik Jena', TRUE),
('SIAL', 'Antibodies.com', TRUE),
('SIAL', 'Antibodysystems', TRUE),
('SIAL', 'ABM Good', TRUE),
('SIAL', 'BigFish', TRUE),
('SIAL', 'UVITEC', TRUE),
('SIAL', 'Charles River', TRUE),
('SIAL', 'Varsome', TRUE),
-- SIAL (non esclusiva)
('SIAL', 'BD', FALSE),
('SIAL', 'EPPENDORF', FALSE),
('SIAL', 'GILSON', FALSE),
('SIAL', 'Thermo Fisher Scientific', FALSE),
('SIAL', 'BIO-RAD', FALSE),
('SIAL', 'HAIER Biomedical', FALSE),
('SIAL', 'Coleparmer/Antylia', FALSE),
('SIAL', 'Ohaus', FALSE),
('SIAL', 'MERCK', FALSE),
('SIAL', 'CORNING', FALSE),

-- Starlab
('Starlab srl', 'Starlab srl', TRUE),

-- Tema Ricerca (esclusiva)
('TEMA RICERCA SRL', 'ARBOR', TRUE),
('TEMA RICERCA SRL', 'REALSEQ', TRUE),
('TEMA RICERCA SRL', 'SEQWEEL', TRUE),
('TEMA RICERCA SRL', 'SEEKGENE', TRUE),
('TEMA RICERCA SRL', 'CELLECTA', TRUE),
('TEMA RICERCA SRL', 'EPIGENTEK', TRUE),
('TEMA RICERCA SRL', 'IDT', TRUE),
('TEMA RICERCA SRL', 'ORIGENE', TRUE),
-- Tema Ricerca (non esclusiva)
('TEMA RICERCA SRL', 'BETHYL', FALSE),
('TEMA RICERCA SRL', 'GENEALL', FALSE),
('TEMA RICERCA SRL', 'TOYOBO', FALSE),
('TEMA RICERCA SRL', 'MIRUS', FALSE),
('TEMA RICERCA SRL', 'LUCIGEN', FALSE),
('TEMA RICERCA SRL', 'AFFINITY', FALSE),
('TEMA RICERCA SRL', 'ELABSCIENCE', FALSE),
('TEMA RICERCA SRL', 'BANGS', FALSE),

-- Twin Helix (esclusiva)
('Twin Helix srl', 'Protein Fluidics Inc.', TRUE),
('Twin Helix srl', 'PHC Laboratory Consumables', TRUE),
('Twin Helix srl', 'Logos Biosystems', TRUE),
('Twin Helix srl', 'highQu GmbH', TRUE),
('Twin Helix srl', 'LeGene Biosciences', TRUE),
('Twin Helix srl', 'Ibidi', TRUE),
('Twin Helix srl', 'Altemis Lab', TRUE),
('Twin Helix srl', 'Cell Dynamics', TRUE),
('Twin Helix srl', 'IDYLLE', TRUE),
('Twin Helix srl', 'BiomimX srl', TRUE),
-- Twin Helix (non esclusiva)
('Twin Helix srl', 'NanoEntek', FALSE),
('Twin Helix srl', 'IBA Lifesciences GmbH', FALSE),
('Twin Helix srl', 'IVTech srl', FALSE),
('Twin Helix srl', 'Reprocell Inc.', FALSE),
('Twin Helix srl', 'ELK Biotechnology', FALSE),
('Twin Helix srl', 'Genscript Services & Products', FALSE),
('Twin Helix srl', 'TargetMol Chemicals', FALSE),
('Twin Helix srl', 'CellInk (BICO)', FALSE),
('Twin Helix srl', 'Repligen', FALSE),

-- VWR (esclusiva)
('VWR International srl', 'Avantor', TRUE),
('VWR International srl', 'JT Baker', TRUE),
('VWR International srl', 'QuantaBio', TRUE),
('VWR International srl', 'VWR Collection', TRUE),
('VWR International srl', 'Masterflex', TRUE),
-- VWR (non esclusiva)
('VWR International srl', 'Agilent', FALSE),
('VWR International srl', 'Applichem', FALSE),
('VWR International srl', 'Beckman Coulter', FALSE),
('VWR International srl', 'Bertin technologies', FALSE),
('VWR International srl', 'Biotium', FALSE),
('VWR International srl', 'Biowest', FALSE),
('VWR International srl', 'Brand', FALSE),
('VWR International srl', 'Corning', FALSE),
('VWR International srl', 'Cytiva', FALSE),
('VWR International srl', 'Eppendorf', FALSE),
('VWR International srl', 'Gilson', FALSE),
('VWR International srl', 'Greiner', FALSE),
('VWR International srl', 'Merck', FALSE),
('VWR International srl', 'Oxford Nanopore', FALSE),
('VWR International srl', 'Pall', FALSE),
('VWR International srl', 'Sartorius', FALSE),
('VWR International srl', 'Tecan', FALSE),
('VWR International srl', 'Thermo Fisher Scientific', FALSE),
('VWR International srl', 'Mettler Toledo', FALSE),
('VWR International srl', '3M', FALSE),
('VWR International srl', 'Kimberly-Clark', FALSE),

-- Promega
('PROMEGA', 'Promega', TRUE),

-- Sarstedt
('SARSTEDT', 'Sarstedt', TRUE),

-- Miltenyi
('MILTENYI', 'Miltenyi', TRUE),

-- TebuBio (esclusiva)
('TEBUBIO', 'Trilink Biotechnologies', TRUE),
('TEBUBIO', 'Broadpharm', TRUE),
('TEBUBIO', 'Spirochrome AG', TRUE),
('TEBUBIO', 'Echelon Biosciences', TRUE),
('TEBUBIO', 'EpiCypher Inc.', TRUE),
('TEBUBIO', 'Prodo Laboratories', TRUE),
('TEBUBIO', 'Signagen Laboratories', TRUE),
('TEBUBIO', 'Lifesensors', TRUE),
('TEBUBIO', 'iXcells Biotechnologies', TRUE),
('TEBUBIO', 'Bioauxilium Research', TRUE),
('TEBUBIO', 'Biocolor ltd', TRUE),
('TEBUBIO', 'Biogems', TRUE),
('TEBUBIO', 'Synbio Technologies', TRUE),
-- TebuBio (non esclusiva)
('TEBUBIO', 'Peprotech', FALSE),
('TEBUBIO', 'BPS Bioscience', FALSE),
('TEBUBIO', 'Biolife Solutions', FALSE),
('TEBUBIO', 'Cedarlane Laboratoires', FALSE),
('TEBUBIO', 'Zenbio', FALSE),
('TEBUBIO', 'Cytoskeleton', FALSE),
('TEBUBIO', 'Raybiotech', FALSE),
('TEBUBIO', 'Rockland Immunochemicals', FALSE),
('TEBUBIO', 'Dojindo Europe GMBH', FALSE),
('TEBUBIO', 'Cell Applications', FALSE),
('TEBUBIO', 'PBL Assay Science', FALSE),
('TEBUBIO', 'Targetmol Chemicals', FALSE),
('TEBUBIO', 'Anaspec', FALSE),
('TEBUBIO', 'Genecopoeia', FALSE),
('TEBUBIO', 'Innovative Research', FALSE),
('TEBUBIO', 'Abnova', FALSE),
('TEBUBIO', 'Eurogentec', FALSE),
('TEBUBIO', 'Boster Bio', FALSE),

-- 2Biological
('2BIOLOGICAL INSTRUMENT', 'FINE SCIENCE TOOLS', TRUE),

-- BD
('BECTON DIKINSON (BD)', 'BD', TRUE),

-- Eppendorf
('EPPENDORF', 'EPPENDORF', TRUE),

-- Eurofins
('EUROFINS GENOMICS', 'EUROFINS GENOMICS', TRUE),

-- Illumina
('ILLUMINA', 'ILLUMINA', TRUE),

-- LGC
('LGC STANDARDS', 'ATCC', TRUE),

-- Life Technologies
('LIFE TECHNOLOGIES (THERMOFISHER)', 'Life Technologies', TRUE),
('LIFE TECHNOLOGIES (THERMOFISHER)', 'PEPROTECH', TRUE),
('LIFE TECHNOLOGIES (THERMOFISHER)', 'BETHYL', TRUE),
('LIFE TECHNOLOGIES (THERMOFISHER)', 'GIBCO', TRUE),
('LIFE TECHNOLOGIES (THERMOFISHER)', 'APPLIED BIOSYSTEM', TRUE),

-- Qiagen
('QIAGEN', 'QIAGEN', TRUE),

-- Prodotti Gianni (esclusiva)
('PRODOTTI GIANNI', 'Abcam', TRUE),
('PRODOTTI GIANNI', 'AFG Bioscience LLC', TRUE),
('PRODOTTI GIANNI', 'Arima Genomics Inc', TRUE),
('PRODOTTI GIANNI', 'BIOZOL / Calibre', TRUE),
('PRODOTTI GIANNI', 'Capitainer AB', TRUE),
('PRODOTTI GIANNI', 'Capricorn Scientific GmbH', TRUE),
('PRODOTTI GIANNI', 'Carl Roth', TRUE),
('PRODOTTI GIANNI', 'Genetex International', TRUE),
('PRODOTTI GIANNI', 'GoldenHelix software', TRUE),
('PRODOTTI GIANNI', 'Goodfellow', TRUE),
('PRODOTTI GIANNI', 'Huabio Research Inc', TRUE),
('PRODOTTI GIANNI', 'Ichorbio Ltd', TRUE),
('PRODOTTI GIANNI', 'Immuno-Biological Laboratories Co., Ltd.', TRUE),
('PRODOTTI GIANNI', 'Jotbody', TRUE),
('PRODOTTI GIANNI', 'LCG / Seracare / Linea KPL', TRUE),
('PRODOTTI GIANNI', 'Lexogen GmbH', TRUE),
('PRODOTTI GIANNI', 'NZYtech LDA', TRUE),
('PRODOTTI GIANNI', 'RJH Biosciences', TRUE),
('PRODOTTI GIANNI', 'Sino Biological Inc. / Signalchem', TRUE),
('PRODOTTI GIANNI', 'Sysmex Partec', TRUE),
('PRODOTTI GIANNI', 'Upper Biotech', TRUE),
-- Prodotti Gianni (non esclusiva)
('PRODOTTI GIANNI', 'Abnova', FALSE),
('PRODOTTI GIANNI', 'Antibodies-online Gmbh', FALSE),
('PRODOTTI GIANNI', 'Biologix Group Limited', FALSE),
('PRODOTTI GIANNI', 'BT-Lab ELISA kits', FALSE),
('PRODOTTI GIANNI', 'ChemScene LLC', FALSE),
('PRODOTTI GIANNI', 'Diacron International Srl', FALSE),
('PRODOTTI GIANNI', 'Eagle Biosciences Inc', FALSE),
('PRODOTTI GIANNI', 'ELK Wuhan Biotechnology CO.Ltd.', FALSE),
('PRODOTTI GIANNI', 'FineTest Biotech Co. Ltd', FALSE),
('PRODOTTI GIANNI', 'Immunostep S.L.', FALSE),
('PRODOTTI GIANNI', 'Jackson ImmunoResearch Europe Ltd.', FALSE),
('PRODOTTI GIANNI', 'MyBioSource', FALSE),
('PRODOTTI GIANNI', 'Nordic BioSite AB', FALSE),
('PRODOTTI GIANNI', 'Origene', FALSE),
('PRODOTTI GIANNI', 'Raybiotech', FALSE),
('PRODOTTI GIANNI', 'Serva', FALSE),
('PRODOTTI GIANNI', 'TargetMol Chemicals Inc', FALSE),
('PRODOTTI GIANNI', 'Universal Sequencing Technology Co.', FALSE);
