-- Suppliers/Produttori principali (case madri) estratti dai brand distribuiti
INSERT INTO suppliers (nome, paese, descrizione) VALUES
('10X Genomics', 'USA', 'Single cell and spatial genomics'),
('Abcam', 'UK', 'Anticorpi, proteine e reagenti'),
('Agilent Technologies', 'USA', 'Strumenti analitici e reagenti'),
('Applied Biosystems', 'USA', 'Strumenti PCR e sequenziamento (ThermoFisher)'),
('ATCC', 'USA', 'Linee cellulari e materiali biologici di riferimento'),
('Avanti Polar Lipids', 'USA', 'Lipidi e liposomi per ricerca'),
('Beckman Coulter', 'USA', 'Centrifughe, flow cytometry, automazione laboratorio'),
('BD (Becton Dickinson)', 'USA', 'Flow cytometry, reagenti, plasticware'),
('Bio-Rad', 'USA', 'Elettroforesi, PCR, anticorpi, imaging'),
('BioLegend', 'USA', 'Anticorpi, citometria a flusso, ELISA'),
('Bio-Techne', 'USA', 'Proteine, anticorpi, ELLA cartridges'),
('Bruker Spatial Biology', 'USA', 'Spatial biology / transcriptomics'),
('Cell Signaling Technology', 'USA', 'Anticorpi, kit segnalazione cellulare'),
('Corning', 'USA', 'Plasticware, Falcon, Axygen'),
('Covaris', 'USA', 'Frammentazione ultrasuoni per NGS'),
('Cytiva (GE Healthcare)', 'USA/Sweden', 'Cromatografia, filtrazione, Whatman'),
('DeNovix', 'USA', 'Spettrofotometri e fluorometri'),
('Diagenode', 'Belgium', 'Epigenetica, ChIP, shearing'),
('Enzo Life Sciences', 'USA', 'Reagenti, anticorpi, kit di rilevazione'),
('Eppendorf', 'Germany', 'Pipette, centrifughe, termomixer, consumabili'),
('Eurofins Genomics', 'Germany', 'Oligo, sequenziamento, servizi genomici'),
('FINE SCIENCE TOOLS', 'Germany', 'Strumenti chirurgici per ricerca'),
('GIBCO', 'USA', 'Terreni di coltura e sieri (ThermoFisher)'),
('Gilson', 'USA/France', 'Pipette e liquid handling'),
('Greiner Bio-One', 'Austria', 'Plasticware, multiwell, tubes'),
('Hettich', 'Germany', 'Centrifughe'),
('Ibidi', 'Germany', 'Camere per microscopia e cell culture'),
('IDT (Integrated DNA Technologies)', 'USA', 'Oligo, gBlocks, CRISPR reagents'),
('IKA', 'Germany', 'Agitatori, stirrer, omogenizzatori'),
('Illumina', 'USA', 'Sequenziatori NGS e reagenti'),
('InvivoGen', 'USA/France', 'Reagenti innate immunity, plasmidi reporter'),
('Jackson ImmunoResearch', 'USA', 'Anticorpi secondari'),
('Lonza', 'Switzerland', 'Coltura cellulare, trasfezione, reagenti'),
('MACHEREY-NAGEL', 'Germany', 'Kit estrazione, purificazione, TLC'),
('Merck / Sigma-Aldrich / Millipore', 'Germany/USA', 'Chemicals, reagenti, filtrazione, anticorpi'),
('Miltenyi Biotec', 'Germany', 'Cell separation, flow cytometry, reagenti'),
('Mission Bio', 'USA', 'Single-cell DNA+protein analysis'),
('New England Biolabs (NEB)', 'USA', 'Enzimi di restrizione, clonaggio, NGS library prep'),
('Oxford Nanopore Technologies', 'UK', 'Sequenziamento nanopore'),
('Peprotech', 'USA', 'Citochine e fattori di crescita'),
('Promega', 'USA', 'Kit luciferasi, purificazione, PCR, clonaggio'),
('Qiagen', 'Germany', 'Kit estrazione DNA/RNA, PCR, NGS'),
('Revvity (PerkinElmer)', 'USA', 'Imaging, screening, reagenti'),
('Roche', 'Switzerland', 'Reagenti, KAPA, diagnostica molecolare'),
('Santa Cruz Biotechnology', 'USA', 'Anticorpi, siRNA, chemicals'),
('Sarstedt', 'Germany', 'Plasticware, provette, pipette'),
('Sartorius', 'Germany', 'Bilance, filtrazione, bioreattori'),
('Selleck Chemicals', 'USA', 'Inibitori, compound libraries'),
('Sino Biological', 'China', 'Proteine ricombinanti, anticorpi'),
('Starlab', 'Germany', 'Puntali, consumabili laboratorio'),
('StemCell Technologies', 'Canada', 'Reagenti per cellule staminali e immunologia'),
('Takara Bio', 'Japan', 'Clonaggio, PCR, retrovirus, single cell'),
('Thermo Fisher Scientific', 'USA', 'Reagenti, strumenti, Life Technologies, Invitrogen, Gibco'),
('Trilink Biotechnologies', 'USA', 'mRNA, nucleotidi modificati, oligo'),
('Twist Bioscience', 'USA', 'Geni sintetici, librerie NGS, oligo'),
('VWR / Avantor', 'USA', 'Chemicals, consumabili, strumentazione'),
('Zymo Research', 'USA', 'Kit epigenetica, purificazione DNA/RNA')
ON CONFLICT (nome) DO NOTHING;
